[package]
name = "jxl_macros"
description = "High performance Rust implementation of a JPEG XL decoder - supporting macros"
version = "0.1.0"
readme = "../README.md"
keywords = ["jpeg-xl", "decoder"]
categories = ["multimedia::images"]
authors = ["Luca Versari <veluca93@gmail.com>"]
repository = "https://github.com/libjxl/jxl-rs"
edition = "2024"
license = "BSD-3-Clause"

[lib]
proc-macro = true

[dependencies]
proc-macro-error2 = "2.0.1"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0.90", features = ["extra-traits", "full"] }

[lints]
workspace = true
