[package]
name = "jxl"
version = "0.1.0"
authors = ["Luca Versari <veluca93@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
byteorder = "1.4.3"
num-derive = "0.3"
num-traits = "0.2.14"
array-init = "2.0.0"
half = "1.7.1"
tracing = "0.1.40"
jxl_headers_derive = { path = "../jxl_headers_derive" }

[features]
debug_tools = []

[lints]
workspace = true
