[package]
name = "jxl-image-rs-integration"
description = "JPEG XL decoder integration for the image crate"
version = "0.7.3"
readme = "../README.md"
keywords = ["jpeg-xl", "decoder", "image"]
categories = ["multimedia::images"]
authors = ["Helmut Januschka <helmut@januschka.com>"]
repository = "https://github.com/libjxl/jxl-rs"
edition = "2024"
license = "BSD-3-Clause"
rust-version.workspace = true

[dependencies]
bytemuck = "1.24.0"
image = { version = "0.25.9", default-features = false }
jxl = { path = "../jxl", version = "=0.7.3", default-features = false }

[features]
default = ["all-simd"]

all-simd = ["jxl/all-simd"]
sse42 = ["jxl/sse42"]
avx = ["jxl/avx"]
avx512 = ["jxl/avx512"]
neon = ["jxl/neon"]
simd128 = ["jxl/simd128"]

[lints]
workspace = true
